### ISSUE TITLE
Create routes, server, and connect other components

### ISSUE THREAD

**Issue by kserra1** [kserra1/CS326Team2#46]
Develops the necessary routes, server setup, and integrates various components for the backend application. This includes defining API endpoints, setting up the Express.js server, and ensuring proper connections between different parts of the system, such as databases, controllers, and middleware, to ensure communication and functionality across the application.

**Comment by AtharvePandey** [comment]
Closing this, some merge previously had already resolved this issue, we just forgot to link it
