### ISSUE TITLE
Update posts for likes, comments, deletions and pin post.

### ISSUE THREAD

**Issue by aidobrien** [kserra1/CS326Team2#65]

**Comment by BrianCapobianco22** [comment]
I will be implementing and making sure that you can delete a recipe and delete a comment

**Comment by kserra1** [comment]
Makes sense

**Comment by BrianCapobianco22** [comment]
I will also make a function called "pin post" to allow different posts to be marked as "pinned.

**Comment by BrianCapobianco22** [comment]
The commit i just did for the pin post is supposed to be "65" not "66"

**Comment by AtharvePandey** [comment]
already resolved, see most recent merge onto main
